// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/khu-dev/khumu-club/ent/club"
	"github.com/khu-dev/khumu-club/ent/likeclub"
	"github.com/khu-dev/khumu-club/ent/predicate"
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LikeClubUpdate is the builder for updating LikeClub entities.
type LikeClubUpdate struct {
	config
	hooks    []Hook
	mutation *LikeClubMutation
}

// Where adds a new predicate for the LikeClubUpdate builder.
func (lcu *LikeClubUpdate) Where(ps ...predicate.LikeClub) *LikeClubUpdate {
	lcu.mutation.predicates = append(lcu.mutation.predicates, ps...)
	return lcu
}

// SetUsername sets the "username" field.
func (lcu *LikeClubUpdate) SetUsername(s string) *LikeClubUpdate {
	lcu.mutation.SetUsername(s)
	return lcu
}

// SetCreatedAt sets the "created_at" field.
func (lcu *LikeClubUpdate) SetCreatedAt(t time.Time) *LikeClubUpdate {
	lcu.mutation.SetCreatedAt(t)
	return lcu
}

// SetClubID sets the "club" edge to the Club entity by ID.
func (lcu *LikeClubUpdate) SetClubID(id int) *LikeClubUpdate {
	lcu.mutation.SetClubID(id)
	return lcu
}

// SetNillableClubID sets the "club" edge to the Club entity by ID if the given value is not nil.
func (lcu *LikeClubUpdate) SetNillableClubID(id *int) *LikeClubUpdate {
	if id != nil {
		lcu = lcu.SetClubID(*id)
	}
	return lcu
}

// SetClub sets the "club" edge to the Club entity.
func (lcu *LikeClubUpdate) SetClub(c *Club) *LikeClubUpdate {
	return lcu.SetClubID(c.ID)
}

// Mutation returns the LikeClubMutation object of the builder.
func (lcu *LikeClubUpdate) Mutation() *LikeClubMutation {
	return lcu.mutation
}

// ClearClub clears the "club" edge to the Club entity.
func (lcu *LikeClubUpdate) ClearClub() *LikeClubUpdate {
	lcu.mutation.ClearClub()
	return lcu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lcu *LikeClubUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lcu.hooks) == 0 {
		affected, err = lcu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LikeClubMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lcu.mutation = mutation
			affected, err = lcu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lcu.hooks) - 1; i >= 0; i-- {
			mut = lcu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lcu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (lcu *LikeClubUpdate) SaveX(ctx context.Context) int {
	affected, err := lcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lcu *LikeClubUpdate) Exec(ctx context.Context) error {
	_, err := lcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcu *LikeClubUpdate) ExecX(ctx context.Context) {
	if err := lcu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lcu *LikeClubUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   likeclub.Table,
			Columns: likeclub.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: likeclub.FieldID,
			},
		},
	}
	if ps := lcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lcu.mutation.Username(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: likeclub.FieldUsername,
		})
	}
	if value, ok := lcu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: likeclub.FieldCreatedAt,
		})
	}
	if lcu.mutation.ClubCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   likeclub.ClubTable,
			Columns: []string{likeclub.ClubColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: club.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lcu.mutation.ClubIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   likeclub.ClubTable,
			Columns: []string{likeclub.ClubColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: club.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{likeclub.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// LikeClubUpdateOne is the builder for updating a single LikeClub entity.
type LikeClubUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LikeClubMutation
}

// SetUsername sets the "username" field.
func (lcuo *LikeClubUpdateOne) SetUsername(s string) *LikeClubUpdateOne {
	lcuo.mutation.SetUsername(s)
	return lcuo
}

// SetCreatedAt sets the "created_at" field.
func (lcuo *LikeClubUpdateOne) SetCreatedAt(t time.Time) *LikeClubUpdateOne {
	lcuo.mutation.SetCreatedAt(t)
	return lcuo
}

// SetClubID sets the "club" edge to the Club entity by ID.
func (lcuo *LikeClubUpdateOne) SetClubID(id int) *LikeClubUpdateOne {
	lcuo.mutation.SetClubID(id)
	return lcuo
}

// SetNillableClubID sets the "club" edge to the Club entity by ID if the given value is not nil.
func (lcuo *LikeClubUpdateOne) SetNillableClubID(id *int) *LikeClubUpdateOne {
	if id != nil {
		lcuo = lcuo.SetClubID(*id)
	}
	return lcuo
}

// SetClub sets the "club" edge to the Club entity.
func (lcuo *LikeClubUpdateOne) SetClub(c *Club) *LikeClubUpdateOne {
	return lcuo.SetClubID(c.ID)
}

// Mutation returns the LikeClubMutation object of the builder.
func (lcuo *LikeClubUpdateOne) Mutation() *LikeClubMutation {
	return lcuo.mutation
}

// ClearClub clears the "club" edge to the Club entity.
func (lcuo *LikeClubUpdateOne) ClearClub() *LikeClubUpdateOne {
	lcuo.mutation.ClearClub()
	return lcuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (lcuo *LikeClubUpdateOne) Select(field string, fields ...string) *LikeClubUpdateOne {
	lcuo.fields = append([]string{field}, fields...)
	return lcuo
}

// Save executes the query and returns the updated LikeClub entity.
func (lcuo *LikeClubUpdateOne) Save(ctx context.Context) (*LikeClub, error) {
	var (
		err  error
		node *LikeClub
	)
	if len(lcuo.hooks) == 0 {
		node, err = lcuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LikeClubMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lcuo.mutation = mutation
			node, err = lcuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(lcuo.hooks) - 1; i >= 0; i-- {
			mut = lcuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lcuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (lcuo *LikeClubUpdateOne) SaveX(ctx context.Context) *LikeClub {
	node, err := lcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (lcuo *LikeClubUpdateOne) Exec(ctx context.Context) error {
	_, err := lcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcuo *LikeClubUpdateOne) ExecX(ctx context.Context) {
	if err := lcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lcuo *LikeClubUpdateOne) sqlSave(ctx context.Context) (_node *LikeClub, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   likeclub.Table,
			Columns: likeclub.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: likeclub.FieldID,
			},
		},
	}
	id, ok := lcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing LikeClub.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := lcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, likeclub.FieldID)
		for _, f := range fields {
			if !likeclub.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != likeclub.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := lcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lcuo.mutation.Username(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: likeclub.FieldUsername,
		})
	}
	if value, ok := lcuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: likeclub.FieldCreatedAt,
		})
	}
	if lcuo.mutation.ClubCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   likeclub.ClubTable,
			Columns: []string{likeclub.ClubColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: club.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lcuo.mutation.ClubIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   likeclub.ClubTable,
			Columns: []string{likeclub.ClubColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: club.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LikeClub{config: lcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, lcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{likeclub.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
