// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/khu-dev/khumu-club/ent/club"
	"github.com/khu-dev/khumu-club/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	clubFields := schema.Club{}.Fields()
	_ = clubFields
	// clubDescRecommended is the schema descriptor for recommended field.
	clubDescRecommended := clubFields[10].Descriptor()
	// club.DefaultRecommended holds the default value on creation for the recommended field.
	club.DefaultRecommended = clubDescRecommended.Default.(bool)
}
