// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Club is the predicate function for club builders.
type Club func(*sql.Selector)

// LikeClub is the predicate function for likeclub builders.
type LikeClub func(*sql.Selector)
